sudo: required
services:
- docker
addons:
  hosts:
    app
before_install:
- docker build -t eresende/prestashop-app configure  
- docker build -t eresende/prestashop-test test
- docker run -d -e PS_DOMAIN=app -e PS_INSTALL_AUTO=1 -e PS_FOLDER_ADMIN=management -e PS_FOLDER_INSTALL=setup --name app eresende/prestashop-app
- sleep 30;
script:
- docker run --link app:app eresende/prestashop-test /bin/sh -c "ping -c 10 app; xvfb-run -a bundle exec rspec"
