sudo: required
services:
- docker
before_install:
- docker build -t eresende/prestashop-plugin:configured app-plugin
- docker build -t eresende/prestashop-test test
- docker run -d --name app -p 80:80 eresende/prestashop-plugin:configured
- docker ps -a
script:
- docker run --link app:app eresende/prestashop-test /bin/sh -c "xvfb-run -a bundle exec rspec"